package ro.nepa.site.CKAN.Entities;

import ro.nepa.site.CKAN.Entities.RawResponse;
import ro.nepa.site.entities.StationXmlFile;

import javax.persistence.*;
import java.time.Instant;
import java.util.Calendar;

/**
 * <p>
 * Use this class to structure the error response from CKAN Portal.
 * </p>
 */
@Entity
@Table(name = "ErrorResponse")
public class ErrorResponse extends RawResponse {

    /**
     * Stores the id of the table. <br/>
     * Value is autogenerated.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "ErrorResponseID")
    private long errorResponseID;

    /**
     * Foreign key to {@link StationXmlFile}
     */
    @ManyToOne(fetch = FetchType.LAZY, cascade = {CascadeType.MERGE, CascadeType.PERSIST})
    @JoinColumn(name = "StationXmlFileID")
    private StationXmlFile stationXmlFile;

    /**
     * <p>
     *Saves the title of the dataset that could not be uploaded to CKAN Portal.
     * </p>
     */
    @Basic
    @Column(name = "DatasetTitle" )
    private String datasetTitle;

    /**
     * <p>
     * Saves the date when the error occured
     * </p>
     */
    @Basic
    @Column(name = "DateCreated")
    private Calendar dateCreated;

    public String getDatasetTitle() {
        return datasetTitle;
    }

    public void setDatasetTitle(String datasetTitle) {
        this.datasetTitle = datasetTitle;
    }

    public Calendar getDateCreated() {
        return dateCreated;
    }

    public void setDateCreated(Calendar dateCreated) {
        this.dateCreated = dateCreated;
    }

    public long getErrorResponseID() {
        return errorResponseID;
    }

    public void setErrorResponseID(long errorResponseID) {
        this.errorResponseID = errorResponseID;
    }

    public StationXmlFile getStationXmlFile() {
        return stationXmlFile;
    }

    public void setStationXmlFile(StationXmlFile stationXmlFile) {
        this.stationXmlFile = stationXmlFile;
    }
}
